### ISSUE TITLE
Query: running pretrained model in python

### ISSUE THREAD

**Issue by Ahmad-noborders** [MorinoseiMorizo/jparacrawl-finetune#1]
hi every one,

i wanted to use pretrained models in python but it do not have bpe file i.e 
`ja2en= TransformerModel.from_pretrained(
  '/content/drive/My Drive/Translation/big',
  checkpoint_file='bigpretrain.pt',  
  data_name_or_path='/content/drive/My Drive/Translation/big',
  bpe='sentencepiece',
 bpe_codes='bpecodes'
  )`
where can I find bpecode file .
i tried it with these two parameters 
`  encoder_embed_path= '/content/drive/My Drive/Translation/enja_spm_models/spm.en.nopretok.vocab',
  pretrained_embed_path='/content/drive/My Drive/Translation/enja_spm_models/spm.en.nopretok.model'`

And then used `ja2en.translate ('こんにちは')` but it is giving 

> '▁ 割 譲'
This result for any text

I also tried this 
`!fairseq-generate '/content/drive/My Drive/Translation/big'  \
    --gen-subset test \
    --path '/content/drive/My Drive/Translation/big/bigpretrain.pt' \
    --beam 5  --source-lang ja --target-lang en   --batch-size 128 --remove-bpe | tee '/content/drive/My Drive/Translation/data/tgt-val.txt'`

And it gives this error

> FileNotFoundError: Dataset not found: test (/content/drive/My Drive/Translation/big)

**Comment by cabhijith** [comment]
@Ahmad-noborders What did you use to create your own BPE file?

**Comment by Ahmad-noborders** [comment]
i  Figure it out. @MorinoseiMorizo thank you so much for this repo
@cabhijith  its already given  [here](http://www.kecl.ntt.co.jp/icl/lirg/jparacrawl/release/1.0/spm_models/en-ja_spm.tar.gz)
use this File and sentencepiece as bpe

**Comment by MorinoseiMorizo** [comment]
Hi @Ahmad-noborders @cabhijith!
Thank you for creating the issue and the help.
I just want to say thanks and I'm happy to hear that you have solved the issue.

**Comment by cabhijith** [comment]
Yup, I had used that and it worked. Thanks @Ahmad-noborders . Also, for anyone in the future, I had to change the name of the BPE file to ```sentencepiece.bpe.model``` to get it to work. Otherwise, fairseq was throwing a NameSpace error. 

Also, Thank You @MorinoseiMorizo for the pre-trained models. Works really well.
