### ISSUE TITLE
Unable to reproduce the results reported in JParaCrawl paper

### ISSUE THREAD

**Issue by xinyiz1019** [MorinoseiMorizo/jparacrawl-finetune#5]
I downloaded big and base models from http://www.kecl.ntt.co.jp/icl/lirg/jparacrawl/ and I evaluated the models using the decode.sh script provided in this repository.
However, I couldn't reproduce the evaluation results reported in your paper. 

Here's an example when testing the big model on the ASPEC dataset.

In the paper, the BLEU score of the English-Japanese model reaches 24.7, while in my experiment, the results look like this:
BLEU+case.mixed+numrefs.1+smooth.exp+tok.intl+version.1.5.0 = 19.4 50.7/25.6/13.9/7.9 (BP = 1.000 ratio = 1.014 hyp_len = 50957 ref_len = 50272)

Also, for the Japanese-English model, the result in the paper is 18.3, while my experiment gives this:
BLEU+case.mixed+numrefs.1+smooth.exp+tok.intl+version.1.5.0 = 20.1 57.0/27.2/15.2/8.9 (BP = 0.938 ratio = 0.940 hyp_len = 43409 ref_len = 46174)

Am I missing anything here?
Thanks in advance for any help!

**Comment by MorinoseiMorizo** [comment]
Hi,

I'm very sorry for the late reply.
I have not noticed.

As described in the paper, we NFKC normalized all the test sets.
For the English-Japanese model, this normalization procedure changes the score.
I uploaded the NFKC normalization scripts here:
https://github.com/MorinoseiMorizo/jparacrawl-finetune/blob/master/scripts/nfkc_normalizer.py

I have no suggestions for the Japanese-English model, but I think you can still use your score as the baseline.

Best,
